# config.py
# note: you can have multiple prefixes, ex: ("-","!","?")
BOT_PREFIX = "INSERT_YOUR_PREFIXES_HERE"

# Discord
TOKEN = "INSERT_YOUR_DISCORD_TOKEN_HERE"

# OpenWeather
WEATHER_TOKEN = "INSERT_YOUR_OPENWEATHER_TOKEN_HERE"

# Reddit
REDDIT_CLIENT_ID = "INSERT_YOUR_CLIENTID_HERE"
REDDIT_SECRET = "INSERT_YOUR_SECRET_HERE"
REDDIT_NAME = "INSERT_YOUR_NAME_HERE"

# Animu
ANIMU_KEY = "INSERT_YOUR_ANIMU_KEY_HERE"
